### ISSUE TITLE
Search - double load

### ISSUE THREAD

**Issue by Tereseus** [denisakaden/Jammming#3]
For some reason I have to click search twice to search for your project. I went through your spotify.js and  your app.js and wasn't able to figure out why I had to do that. It must have something to do with the redirect although you wrote your redirect correctly. Not sure if this is an issue you have as well and it could just be my browser needing to be cleansed. 

Good job with what you did in spotify.js though, you wrote it very cleanly. One thing I would say is to invoke Spotfiy.getAccessToken in App.js right under where you bind search, so that the access token is received on load because that might be causing the double load. Just an idea you can play around with.

**Comment by denisakaden** [comment]
The first click is a reference to your spotify account
